# START # TO USE JEKYLL LIBDOC LOCALLY AS REMOTE THEME
remote_theme: olivier3lanc/Jekyll-LibDoc
plugins:
  - jekyll-remote-theme
# END # TO USE JEKYLL LIBDOC LOCALLY AS REMOTE THEME
title: IT Automotive Design System
description: >- # Description of the docs. (>- means to ignore newlines until next param)
  Documentation of ITADS front-end UI framework
defaults:
  -
    values:
      layout: libdoc/page
kramdown:
    syntax_highlighter_opts:
        disable: true
sass:
    style: compressed
